const Images = {
    Pictures: {
      arrow: require('../assets/images/vector.png'),
      search1:require('../assets/images/search1.png'),
      search2:require('../assets/images/search2.png'),
      search3:require('../assets/images/search3.png'),
      search:require('../assets/images/search.png'),
      home:require('../assets/images/home.png'),
      notification:require('../assets/images/noti.png'),
      appIcon:require('../assets/images/appIcon.png'),
      product:require('../assets/images/product.png'),
      wrench:require('../assets/images/wrench.png'),
      homeIcon:require('../assets/images/homeIcon.png'),
      plus:require('../assets/images/plus.png'),
      measage:require('../assets/images/measageIcon.png'),
      profile:require('../assets/images/profileIcon.png'),
      category:require('../assets/images/category.png'),
      eyeicon: require('../assets/images/eyeicon.png'),
      eye: require('../assets/images/eye.png'),
      question: require('../assets/images/question.png'),
      filter:require('../assets/images/filter.png'),
      dummy: require('../assets/images/dummy.png'),
      orangePlus: require('../assets/images/orangePlus.png'),
      location: require('../assets/images/location.png'),
      girl: require('../assets/images/girl.png'),
      services: require('../assets/images/services.png'),
      downarrow: require('../assets/images/downarrow.png'),
      plumber: require('../assets/images/plumber.png'),
      paint: require('../assets/images/paint.png'),
      door :require('../assets/images/door.png'),
      electricity: require('../assets/images/electricity.png'),
      fences :require('../assets/images/fences.png'),
      construction :require('../assets/images/construction.png'),
      arrowLeft :require('../assets/images/arrowLeft.png'),
      dots :require('../assets/images/3dots.png'),
      textarea: require('../assets/images/textarea.png'),
      checkblue: require('../assets/images/checkblue.png'),
      uncheck: require('../assets/images/uncheck.png')
    }

}
export { Images }
